### PR TITLE
create indonesian translations

### PR DESCRIPTION
**Pull request by ykris45**
Hello My Name is Chris from The Republic of Indonesia. I have succeeded in translating the Ergo wallet app into Indonesian as the national language of my country. I have worked as a software translator on various projects for 5 years. Thank You

### CODE REVIEW

**Comment by aslesarenko** [comment]
@ykris45, have you checked how the app runs with your translation, does all the labels fit into the screen etc.?

**Comment by ykris45** [comment]
> @ykris45, have you checked how the app runs with your translation, does all the labels fit into the screen etc.?

i dont have SDK android and IOS testflight to build my translation. maybe all the labels fit in screen bro, could you help to test it

**Comment by ykris45** [comment]
@aslesarenko lets do workflow again sir. i has been fix this code error

**Comment by ykris45** [comment]
@MrStahlfelge lets merge bro. hehehe

**Review by MrStahlfelge — APPROVED** [review]

**Comment by ykris45** [comment]
thanks you benjamin. God Bless You

**Pull request merged**
