### PR TITLE
Update ProGuard to version 7.2.1 (compatible with AGP7)

### PR DESCRIPTION
**Pull request by mrjameshamilton**
Updates to the latest ProGuard version which is compatible with AGP7 https://www.guardsquare.com/manual/setup/gradleplugin

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Hi, AGP7 enforces R8 and won't use ProGuard any more. 
With R8, signing a transaction is not possible at the moment: https://issuetracker.google.com/issues/223424356

So what is the reason for this upgrade?

**Comment by mrjameshamilton** [comment]
HI @MrStahlfelge ! It's still possible to use ProGuard with AGP7. But the integration has changed slightly and there is a new Gradle plugin with a `proguard` block; the integration in this PR should work with AGP7 as well.

**Comment by MrStahlfelge** [comment]
Okay, that's great to hear. Can you please update the PR to use AGP7 with proguard so I can check if it works?

**Comment by MrStahlfelge** [comment]
Ah I see that the trick is to disable optimization by AGP and do it by Proguard plugin. Is this possible on desktop as well? 
(There's a branch preparing a desktop implementation)

Also, if you have any suggestions on the ProGuard config, feel free to improve it. The Scala libraries were hard to get working.

**Pull request closed without merging**
